#- name: deploy Docker Compose stack
# community.docker.docker_compose:
#   project_src: /opt/monitoring
#   files:
#   - docker-compose.yml
- name: docker-compose up
  shell: "docker-compose up -d"  
  args: 
    chdir: "/opt/monitoring"
